FROM almalinux:9

# ARG course="DevOps" \
#     learned_by="Prudhvi Raj" \
#     percentage="80%" \
#     student="loki"
# RUN echo "${learned_by} expert in ${course}" >  /tmp/about.txt
# RUN echo "HI ${student}" >> /tmp/about.txt
# CMD [ "sleep","1000" ]

RUN useradd raj
#USER ${username:-some_user}
ARG username="prudhvi"
USER $username > /tmp/test.txt
# ...